### PR TITLE
Add Email validation

### PR DESCRIPTION
**Pull request by bimbolabuari**
# Portfolio Microverse Project  🥇 

 > This PR adds a project about building a portfolio with  HTML, CSS, and JS that demonstrates the knowledge of Semantic HTML, flexbox, background properties, and mobile-first responsiveness, Responsive web design, CSS media query, DOM Manipulation, Event listener, arrow function, let and const, Arrays, Object, String interpolation, Array method, client side form validation.

## Built With 😉 

- Semantic HTML & CSS
-  JavaScript

## Live Preview  👍 

[Live Preview Link](https://deploy-preview-12--bimbola-mv-portfolio.netlify.app/)

### CODE REVIEW

**Review by smcommits — COMMENTED** [review]
Hi @bimbolabuari, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

Please make sure all the linter checks are green before requesting a review. As eslint is failing, this code review request is invalid. 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by smcommits** [comment]
@bimbolabuari I can see that you fixed the linter errors. Please ignore the last message. Luckily, I haven't yet marked the request as invalidated.

**Review by smcommits — APPROVED** [review]
### Status: Approved 👍🏽 

Hi @bimbolabuari, 

## You have done a great job! Your project is complete. This PR is now approved. You can go ahead and merge the branch. Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**Comment by bimbolabuari** [comment]
@smcommits, Thanks for approving my project 🚀

**Pull request merged**
